/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope

import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by VitePWA
precacheAndRoute(self.__WB_MANIFEST)

// ---------------------------------------------------------------------------
// Push event — receive push notifications and display them
// ---------------------------------------------------------------------------
self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return

  const data = event.data.json()

  const options = {
    body: data.body,
    icon: data.icon || '/icons/icon-192.png',
    badge: data.badge || '/icons/icon-192.png',
    tag: data.tag,
    data: data.data || {},
    actions: data.actions || [],
    vibrate: [100, 50, 100],
    renotify: !!data.tag, // Replace existing notification with same tag
  }

  event.waitUntil(
    self.registration.showNotification(data.title || 'Jugalbandi', options),
  )
})

// ---------------------------------------------------------------------------
// Notification click — deep-link based on notification data
// ---------------------------------------------------------------------------
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()

  const url = event.notification.data?.url || '/'

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clients) => {
        // Focus existing window if available
        for (const client of clients) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.navigate(url)
            return client.focus()
          }
        }
        // Open new window if none found
        return self.clients.openWindow(url)
      }),
  )
})

// ---------------------------------------------------------------------------
// Push subscription change — re-subscribe when subscription expires
// ---------------------------------------------------------------------------
self.addEventListener('pushsubscriptionchange', ((event: Event & { oldSubscription?: PushSubscription; waitUntil: (p: Promise<unknown>) => void }) => {
  event.waitUntil(
    self.registration.pushManager
      .subscribe(event.oldSubscription?.options ?? { userVisibleOnly: true })
      .then((subscription) => {
        // Post to the app to update the backend
        return self.clients.matchAll().then((clients) => {
          clients.forEach((client) => {
            client.postMessage({
              type: 'PUSH_SUBSCRIPTION_CHANGE',
              subscription: subscription.toJSON(),
            })
          })
        })
      }),
  )
}) as EventListener)
