import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {
  ApplicationServer,
  importVapidKeys,
  PushMessageError,
  type PushSubscription as WebPushSubscription,
} from "jsr:@negrel/webpush@0.5.0";
import { verifyServiceRole, corsHeaders } from "../_shared/auth.ts";
import type { SupabaseClient } from "jsr:@supabase/supabase-js@2";
import { shouldSuppressNegative, recordInteraction } from "../_shared/health-monitor.ts";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface QueuedNotification {
  id: string;
  user_id: string;
  category: string;
  title: string;
  body: string;
  data: Record<string, unknown> | null;
  actions: { action: string; title: string }[] | null;
  tag: string | null;
  urgency: string | null;
  status: string;
  scheduled_for: string;
  retry_count: number;
  max_retries: number;
}

interface Subscription {
  id: string;
  endpoint: string;
  p256dh: string;
  auth_key: string;
}

interface NotificationPreferences {
  enabled: boolean;
  quiet_hours_start: string | null;
  quiet_hours_end: string | null;
  categories_enabled: Record<string, boolean> | null;
  timezone: string;
}

interface ProcessingSummary {
  processed: number;
  delivered: number;
  failed: number;
  rescheduled: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const BATCH_SIZE = 50;

// ---------------------------------------------------------------------------
// VAPID Key Helpers
// ---------------------------------------------------------------------------

/**
 * Decode a base64url string to Uint8Array.
 */
function base64urlToBytes(b64url: string): Uint8Array {
  const b64 = b64url.replace(/-/g, "+").replace(/_/g, "/");
  const pad = (4 - (b64.length % 4)) % 4;
  const padded = b64 + "=".repeat(pad);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Encode Uint8Array to base64url string (no padding).
 */
function bytesToBase64url(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) {
    binary += String.fromCharCode(b);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * Convert raw base64url-encoded VAPID keys (as generated by web-push CLI)
 * into the JWK-based ExportedVapidKeys format that @negrel/webpush expects.
 *
 * Public key: 65 bytes uncompressed EC point (0x04 || x[32] || y[32])
 * Private key: 32 bytes raw "d" parameter
 */
function rawKeysToJwk(
  publicKeyB64: string,
  privateKeyB64: string,
): { publicKey: JsonWebKey; privateKey: JsonWebKey } {
  const pubBytes = base64urlToBytes(publicKeyB64);
  const privBytes = base64urlToBytes(privateKeyB64);

  // Extract x, y from uncompressed public key (skip 0x04 prefix)
  const x = bytesToBase64url(pubBytes.slice(1, 33));
  const y = bytesToBase64url(pubBytes.slice(33, 65));
  const d = bytesToBase64url(privBytes);

  const publicKey: JsonWebKey = {
    kty: "EC",
    crv: "P-256",
    x,
    y,
    ext: true,
  };

  const privateKey: JsonWebKey = {
    kty: "EC",
    crv: "P-256",
    x,
    y,
    d,
    ext: true,
  };

  return { publicKey, privateKey };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseHHMM(hhmm: string): number {
  const [h, m] = hhmm.split(":").map(Number);
  return h * 60 + m;
}

function isInQuietHours(
  prefs: NotificationPreferences,
  now: Date,
): boolean {
  if (!prefs.quiet_hours_start || !prefs.quiet_hours_end) return false;

  const fmt = new Intl.DateTimeFormat("en-GB", {
    timeZone: prefs.timezone || "Europe/London",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });

  const localTime = fmt.format(now);
  const nowMinutes = parseHHMM(localTime);
  const startMinutes = parseHHMM(prefs.quiet_hours_start);
  const endMinutes = parseHHMM(prefs.quiet_hours_end);

  if (startMinutes <= endMinutes) {
    return nowMinutes >= startMinutes && nowMinutes < endMinutes;
  } else {
    return nowMinutes >= startMinutes || nowMinutes < endMinutes;
  }
}

function getQuietHoursEndUTC(prefs: NotificationPreferences): string {
  const now = new Date();
  const tz = prefs.timezone || "Europe/London";

  const dateFmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  const localDateStr = dateFmt.format(now);

  const endTime = prefs.quiet_hours_end || "07:00";
  const [endH, endM] = endTime.split(":").map(Number);

  const utcStr = now.toLocaleString("en-US", { timeZone: "UTC" });
  const tzStr = now.toLocaleString("en-US", { timeZone: tz });
  const offsetMs = new Date(utcStr).getTime() - new Date(tzStr).getTime();

  const localMidnight = new Date(localDateStr + "T00:00:00Z");
  const targetLocal = new Date(
    localMidnight.getTime() + endH * 3600_000 + endM * 60_000,
  );
  const targetUTC = new Date(targetLocal.getTime() + offsetMs);

  if (targetUTC.getTime() <= now.getTime()) {
    targetUTC.setTime(targetUTC.getTime() + 86_400_000);
  }

  return targetUTC.toISOString();
}

function buildPayloadJson(notification: QueuedNotification): string {
  return JSON.stringify({
    title: notification.title,
    body: notification.body,
    icon: "/icons/icon-192.png",
    badge: "/icons/icon-192.png",
    tag: notification.tag || notification.category,
    data: {
      url: notification.data?.url || "/",
      notificationId: notification.id,
      category: notification.category,
      ...notification.data,
    },
    actions: notification.actions || [],
  });
}

function mapUrgency(
  urgency: string | null,
): "very-low" | "low" | "normal" | "high" {
  switch (urgency) {
    case "high":
      return "high";
    case "low":
      return "low";
    case "very-low":
      return "very-low";
    default:
      return "normal";
  }
}

// ---------------------------------------------------------------------------
// Core processing
// ---------------------------------------------------------------------------

async function processNotification(
  supabase: SupabaseClient,
  notification: QueuedNotification,
  appServer: ApplicationServer,
  summary: ProcessingSummary,
): Promise<void> {
  await supabase
    .from("notification_queue")
    .update({ status: "processing" })
    .eq("id", notification.id);

  // 5:1 ratio guard: suppress negative-valence notifications if ratio is unhealthy
  const negativeCategories = ["streak_warning", "nudge", "task_deadline"];
  if (negativeCategories.includes(notification.category)) {
    const suppress = await shouldSuppressNegative(supabase, notification.user_id);
    if (suppress) {
      await supabase
        .from("notification_queue")
        .update({
          status: "cancelled",
          error_message: "Suppressed: 5:1 ratio unhealthy",
        })
        .eq("id", notification.id);

      await logAttempt(
        supabase, notification.id, null, "cancelled",
        "Suppressed by 5:1 ratio enforcement", 0,
      );
      summary.failed++;
      return;
    }
  }

  const { data: subscriptions } = await supabase
    .from("push_subscriptions")
    .select("id, endpoint, p256dh, auth_key")
    .eq("user_id", notification.user_id)
    .eq("active", true);

  if (!subscriptions || subscriptions.length === 0) {
    await supabase
      .from("notification_queue")
      .update({
        status: "failed",
        error_message: "No active push subscriptions",
        error_code: 0,
      })
      .eq("id", notification.id);

    await logAttempt(supabase, notification.id, null, "failed", "No active push subscriptions", 0);
    summary.failed++;
    return;
  }

  const { data: prefs } = await supabase
    .from("notification_preferences")
    .select("enabled, quiet_hours_start, quiet_hours_end, categories_enabled, timezone")
    .eq("user_id", notification.user_id)
    .maybeSingle();

  const preferences: NotificationPreferences = prefs || {
    enabled: true,
    quiet_hours_start: null,
    quiet_hours_end: null,
    categories_enabled: null,
    timezone: "Europe/London",
  };

  if (!preferences.enabled) {
    await supabase
      .from("notification_queue")
      .update({ status: "cancelled", error_message: "Notifications disabled by user" })
      .eq("id", notification.id);

    await logAttempt(supabase, notification.id, null, "cancelled", "Notifications disabled by user", 0);
    summary.failed++;
    return;
  }

  if (
    preferences.categories_enabled &&
    preferences.categories_enabled[notification.category] === false
  ) {
    await supabase
      .from("notification_queue")
      .update({ status: "cancelled", error_message: `Category '${notification.category}' disabled` })
      .eq("id", notification.id);

    await logAttempt(
      supabase, notification.id, null, "cancelled",
      `Category '${notification.category}' disabled`, 0,
    );
    summary.failed++;
    return;
  }

  const now = new Date();
  if (notification.urgency !== "high" && isInQuietHours(preferences, now)) {
    const rescheduleTime = getQuietHoursEndUTC(preferences);
    await supabase
      .from("notification_queue")
      .update({
        status: "pending",
        scheduled_for: rescheduleTime,
        error_message: "Rescheduled: quiet hours",
      })
      .eq("id", notification.id);

    await logAttempt(
      supabase, notification.id, null, "rescheduled",
      `Quiet hours — rescheduled to ${rescheduleTime}`, 0,
    );
    summary.rescheduled++;
    return;
  }

  const pushData = buildPayloadJson(notification);
  let anySuccess = false;

  for (const sub of subscriptions as Subscription[]) {
    const pushSubscription: WebPushSubscription = {
      endpoint: sub.endpoint,
      keys: {
        p256dh: sub.p256dh,
        auth: sub.auth_key,
      },
    };

    try {
      const subscriber = appServer.subscribe(pushSubscription);
      await subscriber.pushTextMessage(pushData, {
        urgency: mapUrgency(notification.urgency),
        topic: notification.tag || notification.category,
        ttl: 3600,
      });

      // Success
      anySuccess = true;

      await supabase
        .from("push_subscriptions")
        .update({ last_successful_push: new Date().toISOString() })
        .eq("id", sub.id);

      await logAttempt(supabase, notification.id, sub.id, "delivered", null, 201);
    } catch (err) {
      if (err instanceof PushMessageError) {
        const statusCode = err.response?.status ?? 0;

        if (err.isGone() || statusCode === 404) {
          // Dead subscription
          await supabase
            .from("push_subscriptions")
            .update({
              active: false,
              deactivated_at: new Date().toISOString(),
            })
            .eq("id", sub.id);

          await logAttempt(
            supabase, notification.id, sub.id, "subscription_expired",
            `Push endpoint returned ${statusCode}`, statusCode,
          );
        } else if (statusCode === 429 || statusCode >= 500) {
          await logAttempt(
            supabase, notification.id, sub.id, "error",
            `Push endpoint returned ${statusCode}`, statusCode,
          );
        } else {
          const errorBody = await err.response?.text().catch(() => "") ?? "";
          await logAttempt(
            supabase, notification.id, sub.id, "error",
            `HTTP ${statusCode}: ${errorBody.slice(0, 200)}`, statusCode,
          );
        }
      } else {
        await logAttempt(
          supabase, notification.id, sub.id, "error",
          `Exception: ${String(err).slice(0, 200)}`, 0,
        );
      }
    }
  }

  if (anySuccess) {
    await supabase
      .from("notification_queue")
      .update({
        status: "delivered",
        sent_at: new Date().toISOString(),
      })
      .eq("id", notification.id);

    summary.delivered++;
  } else {
    const newRetryCount = notification.retry_count + 1;

    if (newRetryCount < notification.max_retries) {
      await supabase
        .from("notification_queue")
        .update({
          status: "pending",
          retry_count: newRetryCount,
          error_message: "All subscriptions failed, will retry",
        })
        .eq("id", notification.id);
    } else {
      await supabase
        .from("notification_queue")
        .update({
          status: "failed",
          retry_count: newRetryCount,
          error_message: "Max retries exhausted",
        })
        .eq("id", notification.id);
    }

    summary.failed++;
  }
}

async function logAttempt(
  supabase: SupabaseClient,
  queueId: string,
  subscriptionId: string | null,
  status: string,
  errorMessage: string | null,
  errorCode: number,
): Promise<void> {
  await supabase.from("notification_log").insert({
    queue_id: queueId,
    subscription_id: subscriptionId,
    status,
    error_message: errorMessage,
    error_code: errorCode || null,
  });
}

// ---------------------------------------------------------------------------
// Edge Function entrypoint
// ---------------------------------------------------------------------------

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: corsHeaders,
    });
  }

  const auth = verifyServiceRole(req.headers.get("Authorization"));
  if (auth.error) return auth.error;
  const supabase = auth.client;

  const vapidPublicKey = Deno.env.get("VAPID_PUBLIC_KEY");
  const vapidPrivateKey = Deno.env.get("VAPID_PRIVATE_KEY");

  if (!vapidPublicKey || !vapidPrivateKey) {
    return new Response(
      JSON.stringify({ error: "VAPID keys not configured" }),
      { status: 500, headers: corsHeaders },
    );
  }

  // Convert raw base64url keys to JWK and import as CryptoKeyPair
  const jwk = rawKeysToJwk(vapidPublicKey, vapidPrivateKey);
  const vapidKeys = await importVapidKeys(jwk);

  // Create ApplicationServer instance
  const appServer = await ApplicationServer.new({
    contactInformation: "mailto:hello@jugalbandi.app",
    vapidKeys,
  });

  try {
    const { data: queue, error: queueError } = await supabase
      .from("notification_queue")
      .select(
        "id, user_id, category, title, body, data, actions, tag, urgency, status, scheduled_for, retry_count, max_retries",
      )
      .eq("status", "pending")
      .lte("scheduled_for", new Date().toISOString())
      .order("scheduled_for", { ascending: true })
      .limit(BATCH_SIZE);

    if (queueError) {
      console.error("Failed to query notification_queue:", queueError);
      return new Response(
        JSON.stringify({ error: "Failed to query queue", detail: queueError.message }),
        { status: 500, headers: corsHeaders },
      );
    }

    if (!queue || queue.length === 0) {
      return new Response(
        JSON.stringify({ processed: 0, delivered: 0, failed: 0, rescheduled: 0 }),
        { status: 200, headers: corsHeaders },
      );
    }

    // Sort high-urgency first
    const urgencyOrder: Record<string, number> = {
      high: 0,
      normal: 1,
      low: 2,
      "very-low": 3,
    };
    queue.sort((a, b) => {
      const ua = urgencyOrder[a.urgency || "normal"] ?? 1;
      const ub = urgencyOrder[b.urgency || "normal"] ?? 1;
      if (ua !== ub) return ua - ub;
      return new Date(a.scheduled_for).getTime() - new Date(b.scheduled_for).getTime();
    });

    const summary: ProcessingSummary = {
      processed: queue.length,
      delivered: 0,
      failed: 0,
      rescheduled: 0,
    };

    for (const notification of queue as QueuedNotification[]) {
      await processNotification(supabase, notification, appServer, summary);
    }

    return new Response(JSON.stringify(summary), {
      status: 200,
      headers: corsHeaders,
    });
  } catch (err) {
    console.error("send-push unexpected error:", err);
    return new Response(
      JSON.stringify({ error: "Internal error", detail: String(err) }),
      { status: 500, headers: corsHeaders },
    );
  }
});
